# Generated by Django 5.2.6 on 2025-10-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='type',
            field=models.CharField(choices=[('color', 'Color'), ('scent', 'Scent'), ('size', 'Size')], max_length=50, verbose_name='Разновидность'),
        ),
    ]
