# Generated by Django 5.2.6 on 2025-10-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_variation_size_alter_variation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variations',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
