# Generated by Django 5.2.6 on 2025-10-15 08:51

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_variations_delete_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Слаг (URL)'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Слаг (URL)'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Слаг (URL)'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, help_text='Логотип бренда', null=True, upload_to='brands/%Y/%m/%d/', verbose_name='Логотип бренда'),
        ),
        migrations.AlterField(
            model_name='brandtranslation',
            name='name',
            field=models.CharField(help_text='Например: Chanel, Dior, Gucci', max_length=255, verbose_name='Имя бренда'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Если категория верхнего уровня, оставьте поле пустым', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category', verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='categorytranslation',
            name='name',
            field=models.CharField(help_text='Например: Косметика, Для губ, Помада', max_length=255, verbose_name='Имя категории'),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(help_text='Бар код с склада', max_length=255, unique=True, verbose_name='Бар код'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Выберите бренд товара', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.brand', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Выберите категорию товара', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='count',
            field=models.PositiveIntegerField(default=0, help_text='Колчиество товаров с склада', verbose_name='Количество на складе'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Напишите Скидочную цену', max_digits=10, null=True, verbose_name='Скидочная цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Выберите Фото товара', null=True, upload_to='products/%Y/%m/%d/', verbose_name='Фото товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Напишите Цену без скидки', max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='variations',
            field=models.JSONField(blank=True, default=dict, help_text='Например: в таком формате {"цвет": "красный", "объем": "50мл"}', verbose_name='Вариации товара'),
        ),
        migrations.AlterField(
            model_name='producttranslation',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Опишите тоар, его особенности, состав', null=True, verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='producttranslation',
            name='name',
            field=models.CharField(help_text='Например: Помада Rouge Allure (получаю с склада)', max_length=255, verbose_name='Имя товара'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='active',
            field=models.BooleanField(default=True, help_text='Если акция не активна, она не будет отображаться на сайте', verbose_name='Активна ли акция?'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='image',
            field=models.ImageField(blank=True, help_text='Выберите Фото акции/баннера', null=True, upload_to='promotions/%Y/%m/%d/', verbose_name='Фото акции'),
        ),
        migrations.AlterField(
            model_name='promotiontranslation',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Опишите акцию, условия', null=True, verbose_name='Описание акции'),
        ),
        migrations.AlterField(
            model_name='promotiontranslation',
            name='title',
            field=models.CharField(help_text='Например: Летняя распродажа', max_length=255, verbose_name='Название акции'),
        ),
    ]
