# Generated by Django 5.2.6 on 2025-10-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_brand_slug_category_slug_product_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='Слаг (URL)'),
        ),
    ]
