# Generated by Django 5.2.6 on 2025-10-15 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_brand_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
