# Generated by Django 5.2.6 on 2025-10-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, help_text='Оставьте это поле пустым!! Оно будет создано автоматически из имени бренда', null=True, verbose_name='Слаг (URL)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='Оставьте это поле пустым!! Оно будет создано автоматически из имени категории', null=True, unique=True, verbose_name='Слаг (URL)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='Оставьте это поле пустым!! Оно будет создано автоматически из имени товара', null=True, unique=True, verbose_name='Слаг (URL)'),
        ),
    ]
