# Generated by Django 5.2.6 on 2025-11-10 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_brand_slug_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BrandTranslation',
        ),
    ]
