# Generated by Django 5.2.6 on 2025-11-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_delete_brandtranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='name',
            field=models.CharField(default=1, help_text='Например: Chanel, Dior, Gucci', max_length=255, verbose_name='Имя бренда'),
            preserve_default=False,
        ),
    ]
