# Generated by Django 5.2.6 on 2025-11-28 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_brand_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Добавьте Фото галереи товара', upload_to='products/gallery/%Y/%m/%d/', verbose_name='Фото галереи товара')),
                ('alt_text', models.CharField(blank=True, help_text='Добавьте Seo текст для фото (необязательно)', max_length=255, null=True, verbose_name='СЕО текст для фото (необязательно)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='products.product')),
            ],
            options={
                'verbose_name': 'Фото товара',
                'verbose_name_plural': 'Галерея товара',
            },
        ),
    ]
