# Generated by Django 5.2.6 on 2025-11-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_productgallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgallery',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='image',
            field=models.ImageField(upload_to='products/gallery/%Y/%m/%d/'),
        ),
    ]
