# Generated by Django 5.2.6 on 2025-11-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_productgallery_alt_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isRecommended',
            field=models.BooleanField(default=False, help_text='Отметьте, если товар рекомендуется', verbose_name='Рекомендуемый товар'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Добавьте Seo текст(необязательно)', max_length=255, null=True, verbose_name='Seo текст(необязательно)'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='image',
            field=models.ImageField(help_text='Выберите Фото для галереи товара', upload_to='products/gallery/%Y/%m/%d/', verbose_name='Фото товара'),
        ),
    ]
