# Generated by Django 5.2.6 on 2025-12-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_product_isrecommended_alter_productgallery_alt_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='variations',
            field=models.TextField(blank=True, help_text='Введите номера через запятую — 101,102,103', verbose_name='Вариации товара )  # цвет, объем и т.д.'),
        ),
    ]
