# Generated by Django 5.2.6 on 2026-01-15 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_order_alter_product_variations_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='color, scent, size', max_length=50, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип вариации',
                'verbose_name_plural': 'Типы вариаций',
            },
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Заказ продукции', 'verbose_name_plural': 'Заказы продукции'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='variations',
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='Значение вариации')),
                ('color_hex', models.CharField(blank=True, help_text='Для цветов #FFFFFF', max_length=7, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='products.product')),
                ('variation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='products.variationtype')),
            ],
            options={
                'verbose_name': 'Вариация товара',
                'verbose_name_plural': 'Вариации товара',
                'unique_together': {('product', 'variation_type', 'value')},
            },
        ),
        migrations.CreateModel(
            name='ProductVariationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/variations/%Y/%m/%d/')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='products.productvariation')),
            ],
            options={
                'verbose_name': 'Фото вариации',
                'verbose_name_plural': 'Галерея вариации',
            },
        ),
    ]
