# Generated by Django 5.2.6 on 2026-01-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_variationtype_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='last_name',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default=99311, verbose_name='Адрес'),
            preserve_default=False,
        ),
    ]
