# Generated by Django 5.2.6 on 2026-03-02 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_orderitem_options_alter_orderitem_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isOnSale',
            field=models.BooleanField(default=False, help_text='Отметьте, если товар участвует в акции', verbose_name='Акционный товар'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='barcode',
            field=models.CharField(max_length=255, verbose_name='Бар код'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за единицу'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='orders/products/', verbose_name='Изображение товара'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(max_length=255, verbose_name='Название товара'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
    ]
